package com.wss.model.role;

import java.util.Date;

public class Role {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_role.role_cd
     *
     * @mbggenerated Thu Jun 15 10:19:22 CST 2017
     */
    private String roleCd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_role.role_name
     *
     * @mbggenerated Thu Jun 15 10:19:22 CST 2017
     */
    private String roleName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_role.enable_flag
     *
     * @mbggenerated Thu Jun 15 10:19:22 CST 2017
     */
    private String enableFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_role.notes
     *
     * @mbggenerated Thu Jun 15 10:19:22 CST 2017
     */
    private String notes;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_role.create_user
     *
     * @mbggenerated Thu Jun 15 10:19:22 CST 2017
     */
    private String createUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_role.create_method
     *
     * @mbggenerated Thu Jun 15 10:19:22 CST 2017
     */
    private String createMethod;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_role.create_time
     *
     * @mbggenerated Thu Jun 15 10:19:22 CST 2017
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_role.last_upd_user
     *
     * @mbggenerated Thu Jun 15 10:19:22 CST 2017
     */
    private String lastUpdUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_role.last_upd_method
     *
     * @mbggenerated Thu Jun 15 10:19:22 CST 2017
     */
    private String lastUpdMethod;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_role.last_upd_time
     *
     * @mbggenerated Thu Jun 15 10:19:22 CST 2017
     */
    private Date lastUpdTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_role.role_cd
     *
     * @return the value of tb_role.role_cd
     *
     * @mbggenerated Thu Jun 15 10:19:22 CST 2017
     */
    public String getRoleCd() {
        return roleCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_role.role_cd
     *
     * @param roleCd the value for tb_role.role_cd
     *
     * @mbggenerated Thu Jun 15 10:19:22 CST 2017
     */
    public void setRoleCd(String roleCd) {
        this.roleCd = roleCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_role.role_name
     *
     * @return the value of tb_role.role_name
     *
     * @mbggenerated Thu Jun 15 10:19:22 CST 2017
     */
    public String getRoleName() {
        return roleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_role.role_name
     *
     * @param roleName the value for tb_role.role_name
     *
     * @mbggenerated Thu Jun 15 10:19:22 CST 2017
     */
    public void setRoleName(String roleName) {
        this.roleName = roleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_role.enable_flag
     *
     * @return the value of tb_role.enable_flag
     *
     * @mbggenerated Thu Jun 15 10:19:22 CST 2017
     */
    public String getEnableFlag() {
        return enableFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_role.enable_flag
     *
     * @param enableFlag the value for tb_role.enable_flag
     *
     * @mbggenerated Thu Jun 15 10:19:22 CST 2017
     */
    public void setEnableFlag(String enableFlag) {
        this.enableFlag = enableFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_role.notes
     *
     * @return the value of tb_role.notes
     *
     * @mbggenerated Thu Jun 15 10:19:22 CST 2017
     */
    public String getNotes() {
        return notes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_role.notes
     *
     * @param notes the value for tb_role.notes
     *
     * @mbggenerated Thu Jun 15 10:19:22 CST 2017
     */
    public void setNotes(String notes) {
        this.notes = notes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_role.create_user
     *
     * @return the value of tb_role.create_user
     *
     * @mbggenerated Thu Jun 15 10:19:22 CST 2017
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_role.create_user
     *
     * @param createUser the value for tb_role.create_user
     *
     * @mbggenerated Thu Jun 15 10:19:22 CST 2017
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_role.create_method
     *
     * @return the value of tb_role.create_method
     *
     * @mbggenerated Thu Jun 15 10:19:22 CST 2017
     */
    public String getCreateMethod() {
        return createMethod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_role.create_method
     *
     * @param createMethod the value for tb_role.create_method
     *
     * @mbggenerated Thu Jun 15 10:19:22 CST 2017
     */
    public void setCreateMethod(String createMethod) {
        this.createMethod = createMethod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_role.create_time
     *
     * @return the value of tb_role.create_time
     *
     * @mbggenerated Thu Jun 15 10:19:22 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_role.create_time
     *
     * @param createTime the value for tb_role.create_time
     *
     * @mbggenerated Thu Jun 15 10:19:22 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_role.last_upd_user
     *
     * @return the value of tb_role.last_upd_user
     *
     * @mbggenerated Thu Jun 15 10:19:22 CST 2017
     */
    public String getLastUpdUser() {
        return lastUpdUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_role.last_upd_user
     *
     * @param lastUpdUser the value for tb_role.last_upd_user
     *
     * @mbggenerated Thu Jun 15 10:19:22 CST 2017
     */
    public void setLastUpdUser(String lastUpdUser) {
        this.lastUpdUser = lastUpdUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_role.last_upd_method
     *
     * @return the value of tb_role.last_upd_method
     *
     * @mbggenerated Thu Jun 15 10:19:22 CST 2017
     */
    public String getLastUpdMethod() {
        return lastUpdMethod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_role.last_upd_method
     *
     * @param lastUpdMethod the value for tb_role.last_upd_method
     *
     * @mbggenerated Thu Jun 15 10:19:22 CST 2017
     */
    public void setLastUpdMethod(String lastUpdMethod) {
        this.lastUpdMethod = lastUpdMethod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_role.last_upd_time
     *
     * @return the value of tb_role.last_upd_time
     *
     * @mbggenerated Thu Jun 15 10:19:22 CST 2017
     */
    public Date getLastUpdTime() {
        return lastUpdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_role.last_upd_time
     *
     * @param lastUpdTime the value for tb_role.last_upd_time
     *
     * @mbggenerated Thu Jun 15 10:19:22 CST 2017
     */
    public void setLastUpdTime(Date lastUpdTime) {
        this.lastUpdTime = lastUpdTime;
    }
}