package com.xhs.mapper.user;

import com.xhs.entity.user.UserRole;

public interface UserRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_role
     *
     * @mbggenerated Thu Jun 15 10:21:27 CST 2017
     */
    int insert(UserRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_role
     *
     * @mbggenerated Thu Jun 15 10:21:27 CST 2017
     */
    int insertSelective(UserRole record);

}