package com.wss.model.user;

/**
 * @author Administrator
 *
 */
public class UserMenu {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_role_menu.role_cd
     *
     * @mbggenerated Thu Jun 15 10:21:38 CST 2017
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_role_menu.menu_cd
     *
     * @mbggenerated Thu Jun 15 10:21:38 CST 2017
     */
    private String menuCd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_role_menu.menu_name
     *
     * @mbggenerated Thu Jun 15 10:21:38 CST 2017
     */
    private String menuName;


    public String getUserName() {
		return userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_role_menu.menu_cd
     *
     * @return the value of tb_role_menu.menu_cd
     *
     * @mbggenerated Thu Jun 15 10:21:38 CST 2017
     */
    public String getMenuCd() {
        return menuCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_role_menu.menu_cd
     *
     * @param menuCd the value for tb_role_menu.menu_cd
     *
     * @mbggenerated Thu Jun 15 10:21:38 CST 2017
     */
    public void setMenuCd(String menuCd) {
        this.menuCd = menuCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_role_menu.menu_name
     *
     * @return the value of tb_role_menu.menu_name
     *
     * @mbggenerated Thu Jun 15 10:21:38 CST 2017
     */
    public String getMenuName() {
        return menuName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_role_menu.menu_name
     *
     * @param menuName the value for tb_role_menu.menu_name
     *
     * @mbggenerated Thu Jun 15 10:21:38 CST 2017
     */
    public void setMenuName(String menuName) {
        this.menuName = menuName;
    }

}