package com.wss.dao.log;

import com.wss.model.log.RequestLog;

public interface RequestLogMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table request_log_tbl
	 * @mbg.generated  Tue Jan 09 15:46:53 CST 2018
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table request_log_tbl
	 * @mbg.generated  Tue Jan 09 15:46:53 CST 2018
	 */
	int insert(RequestLog record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table request_log_tbl
	 * @mbg.generated  Tue Jan 09 15:46:53 CST 2018
	 */
	int insertSelective(RequestLog record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table request_log_tbl
	 * @mbg.generated  Tue Jan 09 15:46:53 CST 2018
	 */
	int updateByPrimaryKeySelective(RequestLog record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table request_log_tbl
	 * @mbg.generated  Tue Jan 09 15:46:53 CST 2018
	 */
	int updateByPrimaryKey(RequestLog record);
}