package com.xhs.entity.user;

import java.io.Serializable;
import java.util.Date;

public class User implements Serializable{
    /**
	 * serialVersionUID:TODO(用一句话描述这个变量表示什么).
	 * @since JDK 1.6
	 */
	private static final long serialVersionUID = -4400054756066640510L;

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user.id
     *
     * @mbggenerated Thu Jun 01 17:38:13 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user.type
     *
     * @mbggenerated Thu Jun 01 17:38:13 CST 2017
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user.username
     *
     * @mbggenerated Thu Jun 01 17:38:13 CST 2017
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user.fullname
     *
     * @mbggenerated Thu Jun 01 17:38:13 CST 2017
     */
    private String fullname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user.password
     *
     * @mbggenerated Thu Jun 01 17:38:13 CST 2017
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user.sex
     *
     * @mbggenerated Thu Jun 01 17:38:13 CST 2017
     */
    private String sex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user.email
     *
     * @mbggenerated Thu Jun 01 17:38:13 CST 2017
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user.mobilephone
     *
     * @mbggenerated Thu Jun 01 17:38:13 CST 2017
     */
    private String mobilephone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user.createtime
     *
     * @mbggenerated Thu Jun 01 17:38:13 CST 2017
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user.enableflag
     *
     * @mbggenerated Thu Jun 01 17:38:13 CST 2017
     */
    private String enableflag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.id
     *
     * @return the value of tb_user.id
     *
     * @mbggenerated Thu Jun 01 17:38:13 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user.id
     *
     * @param id the value for tb_user.id
     *
     * @mbggenerated Thu Jun 01 17:38:13 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.type
     *
     * @return the value of tb_user.type
     *
     * @mbggenerated Thu Jun 01 17:38:13 CST 2017
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user.type
     *
     * @param type the value for tb_user.type
     *
     * @mbggenerated Thu Jun 01 17:38:13 CST 2017
     */
    public void setType(String type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.username
     *
     * @return the value of tb_user.username
     *
     * @mbggenerated Thu Jun 01 17:38:13 CST 2017
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user.username
     *
     * @param username the value for tb_user.username
     *
     * @mbggenerated Thu Jun 01 17:38:13 CST 2017
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.fullname
     *
     * @return the value of tb_user.fullname
     *
     * @mbggenerated Thu Jun 01 17:38:13 CST 2017
     */
    public String getFullname() {
        return fullname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user.fullname
     *
     * @param fullname the value for tb_user.fullname
     *
     * @mbggenerated Thu Jun 01 17:38:13 CST 2017
     */
    public void setFullname(String fullname) {
        this.fullname = fullname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.password
     *
     * @return the value of tb_user.password
     *
     * @mbggenerated Thu Jun 01 17:38:13 CST 2017
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user.password
     *
     * @param password the value for tb_user.password
     *
     * @mbggenerated Thu Jun 01 17:38:13 CST 2017
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.sex
     *
     * @return the value of tb_user.sex
     *
     * @mbggenerated Thu Jun 01 17:38:13 CST 2017
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user.sex
     *
     * @param sex the value for tb_user.sex
     *
     * @mbggenerated Thu Jun 01 17:38:13 CST 2017
     */
    public void setSex(String sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.email
     *
     * @return the value of tb_user.email
     *
     * @mbggenerated Thu Jun 01 17:38:13 CST 2017
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user.email
     *
     * @param email the value for tb_user.email
     *
     * @mbggenerated Thu Jun 01 17:38:13 CST 2017
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.mobilephone
     *
     * @return the value of tb_user.mobilephone
     *
     * @mbggenerated Thu Jun 01 17:38:13 CST 2017
     */
    public String getMobilephone() {
        return mobilephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user.mobilephone
     *
     * @param mobilephone the value for tb_user.mobilephone
     *
     * @mbggenerated Thu Jun 01 17:38:13 CST 2017
     */
    public void setMobilephone(String mobilephone) {
        this.mobilephone = mobilephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.createtime
     *
     * @return the value of tb_user.createtime
     *
     * @mbggenerated Thu Jun 01 17:38:13 CST 2017
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user.createtime
     *
     * @param createtime the value for tb_user.createtime
     *
     * @mbggenerated Thu Jun 01 17:38:13 CST 2017
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.enableflag
     *
     * @return the value of tb_user.enableflag
     *
     * @mbggenerated Thu Jun 01 17:38:13 CST 2017
     */
    public String getEnableflag() {
        return enableflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user.enableflag
     *
     * @param enableflag the value for tb_user.enableflag
     *
     * @mbggenerated Thu Jun 01 17:38:13 CST 2017
     */
    public void setEnableflag(String enableflag) {
        this.enableflag = enableflag;
    }
}