package com.xhs.entity.user;

import java.util.Date;

public class UserRole {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user_role.username
     *
     * @mbggenerated Thu Jun 15 10:21:27 CST 2017
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user_role.role_cd
     *
     * @mbggenerated Thu Jun 15 10:21:27 CST 2017
     */
    private String roleCd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user_role.role_name
     *
     * @mbggenerated Thu Jun 15 10:21:27 CST 2017
     */
    private String roleName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user_role.create_user
     *
     * @mbggenerated Thu Jun 15 10:21:27 CST 2017
     */
    private String createUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user_role.create_method
     *
     * @mbggenerated Thu Jun 15 10:21:27 CST 2017
     */
    private String createMethod;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user_role.create_time
     *
     * @mbggenerated Thu Jun 15 10:21:27 CST 2017
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user_role.last_upd_user
     *
     * @mbggenerated Thu Jun 15 10:21:27 CST 2017
     */
    private String lastUpdUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user_role.last_upd_method
     *
     * @mbggenerated Thu Jun 15 10:21:27 CST 2017
     */
    private String lastUpdMethod;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user_role.last_upd_time
     *
     * @mbggenerated Thu Jun 15 10:21:27 CST 2017
     */
    private Date lastUpdTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user_role.username
     *
     * @return the value of tb_user_role.username
     *
     * @mbggenerated Thu Jun 15 10:21:27 CST 2017
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user_role.username
     *
     * @param username the value for tb_user_role.username
     *
     * @mbggenerated Thu Jun 15 10:21:27 CST 2017
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user_role.role_cd
     *
     * @return the value of tb_user_role.role_cd
     *
     * @mbggenerated Thu Jun 15 10:21:27 CST 2017
     */
    public String getRoleCd() {
        return roleCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user_role.role_cd
     *
     * @param roleCd the value for tb_user_role.role_cd
     *
     * @mbggenerated Thu Jun 15 10:21:27 CST 2017
     */
    public void setRoleCd(String roleCd) {
        this.roleCd = roleCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user_role.role_name
     *
     * @return the value of tb_user_role.role_name
     *
     * @mbggenerated Thu Jun 15 10:21:27 CST 2017
     */
    public String getRoleName() {
        return roleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user_role.role_name
     *
     * @param roleName the value for tb_user_role.role_name
     *
     * @mbggenerated Thu Jun 15 10:21:27 CST 2017
     */
    public void setRoleName(String roleName) {
        this.roleName = roleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user_role.create_user
     *
     * @return the value of tb_user_role.create_user
     *
     * @mbggenerated Thu Jun 15 10:21:27 CST 2017
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user_role.create_user
     *
     * @param createUser the value for tb_user_role.create_user
     *
     * @mbggenerated Thu Jun 15 10:21:27 CST 2017
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user_role.create_method
     *
     * @return the value of tb_user_role.create_method
     *
     * @mbggenerated Thu Jun 15 10:21:27 CST 2017
     */
    public String getCreateMethod() {
        return createMethod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user_role.create_method
     *
     * @param createMethod the value for tb_user_role.create_method
     *
     * @mbggenerated Thu Jun 15 10:21:27 CST 2017
     */
    public void setCreateMethod(String createMethod) {
        this.createMethod = createMethod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user_role.create_time
     *
     * @return the value of tb_user_role.create_time
     *
     * @mbggenerated Thu Jun 15 10:21:27 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user_role.create_time
     *
     * @param createTime the value for tb_user_role.create_time
     *
     * @mbggenerated Thu Jun 15 10:21:27 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user_role.last_upd_user
     *
     * @return the value of tb_user_role.last_upd_user
     *
     * @mbggenerated Thu Jun 15 10:21:27 CST 2017
     */
    public String getLastUpdUser() {
        return lastUpdUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user_role.last_upd_user
     *
     * @param lastUpdUser the value for tb_user_role.last_upd_user
     *
     * @mbggenerated Thu Jun 15 10:21:27 CST 2017
     */
    public void setLastUpdUser(String lastUpdUser) {
        this.lastUpdUser = lastUpdUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user_role.last_upd_method
     *
     * @return the value of tb_user_role.last_upd_method
     *
     * @mbggenerated Thu Jun 15 10:21:27 CST 2017
     */
    public String getLastUpdMethod() {
        return lastUpdMethod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user_role.last_upd_method
     *
     * @param lastUpdMethod the value for tb_user_role.last_upd_method
     *
     * @mbggenerated Thu Jun 15 10:21:27 CST 2017
     */
    public void setLastUpdMethod(String lastUpdMethod) {
        this.lastUpdMethod = lastUpdMethod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user_role.last_upd_time
     *
     * @return the value of tb_user_role.last_upd_time
     *
     * @mbggenerated Thu Jun 15 10:21:27 CST 2017
     */
    public Date getLastUpdTime() {
        return lastUpdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user_role.last_upd_time
     *
     * @param lastUpdTime the value for tb_user_role.last_upd_time
     *
     * @mbggenerated Thu Jun 15 10:21:27 CST 2017
     */
    public void setLastUpdTime(Date lastUpdTime) {
        this.lastUpdTime = lastUpdTime;
    }
}