package com.wss.model.log;

import java.util.Date;

public class RequestLog {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column request_log_tbl.id
	 * @mbg.generated  Tue Jan 09 15:46:53 CST 2018
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column request_log_tbl.request_date
	 * @mbg.generated  Tue Jan 09 15:46:53 CST 2018
	 */
	private Date requestDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column request_log_tbl.request_ip
	 * @mbg.generated  Tue Jan 09 15:46:53 CST 2018
	 */
	private String requestIp;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column request_log_tbl.request_url
	 * @mbg.generated  Tue Jan 09 15:46:53 CST 2018
	 */
	private String requestUrl;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column request_log_tbl.request_method
	 * @mbg.generated  Tue Jan 09 15:46:53 CST 2018
	 */
	private String requestMethod;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column request_log_tbl.params
	 * @mbg.generated  Tue Jan 09 15:46:53 CST 2018
	 */
	private String params;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column request_log_tbl.response_date
	 * @mbg.generated  Tue Jan 09 15:46:53 CST 2018
	 */
	private Date responseDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column request_log_tbl.response_ip
	 * @mbg.generated  Tue Jan 09 15:46:53 CST 2018
	 */
	private String responseIp;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column request_log_tbl.cost_time
	 * @mbg.generated  Tue Jan 09 15:46:53 CST 2018
	 */
	private String costTime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column request_log_tbl.id
	 * @return  the value of request_log_tbl.id
	 * @mbg.generated  Tue Jan 09 15:46:53 CST 2018
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column request_log_tbl.id
	 * @param id  the value for request_log_tbl.id
	 * @mbg.generated  Tue Jan 09 15:46:53 CST 2018
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column request_log_tbl.request_date
	 * @return  the value of request_log_tbl.request_date
	 * @mbg.generated  Tue Jan 09 15:46:53 CST 2018
	 */
	public Date getRequestDate() {
		return requestDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column request_log_tbl.request_date
	 * @param requestDate  the value for request_log_tbl.request_date
	 * @mbg.generated  Tue Jan 09 15:46:53 CST 2018
	 */
	public void setRequestDate(Date requestDate) {
		this.requestDate = requestDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column request_log_tbl.request_ip
	 * @return  the value of request_log_tbl.request_ip
	 * @mbg.generated  Tue Jan 09 15:46:53 CST 2018
	 */
	public String getRequestIp() {
		return requestIp;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column request_log_tbl.request_ip
	 * @param requestIp  the value for request_log_tbl.request_ip
	 * @mbg.generated  Tue Jan 09 15:46:53 CST 2018
	 */
	public void setRequestIp(String requestIp) {
		this.requestIp = requestIp;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column request_log_tbl.request_url
	 * @return  the value of request_log_tbl.request_url
	 * @mbg.generated  Tue Jan 09 15:46:53 CST 2018
	 */
	public String getRequestUrl() {
		return requestUrl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column request_log_tbl.request_url
	 * @param requestUrl  the value for request_log_tbl.request_url
	 * @mbg.generated  Tue Jan 09 15:46:53 CST 2018
	 */
	public void setRequestUrl(String requestUrl) {
		this.requestUrl = requestUrl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column request_log_tbl.request_method
	 * @return  the value of request_log_tbl.request_method
	 * @mbg.generated  Tue Jan 09 15:46:53 CST 2018
	 */
	public String getRequestMethod() {
		return requestMethod;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column request_log_tbl.request_method
	 * @param requestMethod  the value for request_log_tbl.request_method
	 * @mbg.generated  Tue Jan 09 15:46:53 CST 2018
	 */
	public void setRequestMethod(String requestMethod) {
		this.requestMethod = requestMethod;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column request_log_tbl.params
	 * @return  the value of request_log_tbl.params
	 * @mbg.generated  Tue Jan 09 15:46:53 CST 2018
	 */
	public String getParams() {
		return params;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column request_log_tbl.params
	 * @param params  the value for request_log_tbl.params
	 * @mbg.generated  Tue Jan 09 15:46:53 CST 2018
	 */
	public void setParams(String params) {
		this.params = params;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column request_log_tbl.response_date
	 * @return  the value of request_log_tbl.response_date
	 * @mbg.generated  Tue Jan 09 15:46:53 CST 2018
	 */
	public Date getResponseDate() {
		return responseDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column request_log_tbl.response_date
	 * @param responseDate  the value for request_log_tbl.response_date
	 * @mbg.generated  Tue Jan 09 15:46:53 CST 2018
	 */
	public void setResponseDate(Date responseDate) {
		this.responseDate = responseDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column request_log_tbl.response_ip
	 * @return  the value of request_log_tbl.response_ip
	 * @mbg.generated  Tue Jan 09 15:46:53 CST 2018
	 */
	public String getResponseIp() {
		return responseIp;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column request_log_tbl.response_ip
	 * @param responseIp  the value for request_log_tbl.response_ip
	 * @mbg.generated  Tue Jan 09 15:46:53 CST 2018
	 */
	public void setResponseIp(String responseIp) {
		this.responseIp = responseIp;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column request_log_tbl.cost_time
	 * @return  the value of request_log_tbl.cost_time
	 * @mbg.generated  Tue Jan 09 15:46:53 CST 2018
	 */
	public String getCostTime() {
		return costTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column request_log_tbl.cost_time
	 * @param costTime  the value for request_log_tbl.cost_time
	 * @mbg.generated  Tue Jan 09 15:46:53 CST 2018
	 */
	public void setCostTime(String costTime) {
		this.costTime = costTime;
	}
}