package com.wss.dao.user;

import com.wss.model.user.RoleMenu;

public interface RoleMenuMapper {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_role_menu
     *
     * @mbggenerated Thu Jun 15 10:21:38 CST 2017
     */
    int insert(RoleMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_role_menu
     *
     * @mbggenerated Thu Jun 15 10:21:38 CST 2017
     */
    int insertSelective(RoleMenu record);


}